---
title: "Collected Works of Tyler B. Naes"
output: 
  flexdashboard::flex_dashboard:
    theme: spacelab
    source: embed
    smart: false
runtime: shiny
---

```{r include = FALSE}

# DESCRIPTION

  # This code chunk is for preprocessing only.
  # If you are not transforming any variables, ignore this section.
  # The variables created in this chunk make it easier to create a dashboard.



# LOAD PACKAGES

library( DT )
library( ggmap )
library( shiny )
library( knitr )
library( pander )
library( leaflet )
library( viridis )
library( rsconnect )
library( tidyverse )
library( flexdashboard )



# READ IN DATA

url <- paste0("https://github.com/DS4PS/Data-",
              "Science-Class/blob/master/DATA",
              "/TempeTrafficAccidents.rds?raw=true")

dat <- readRDS( gzcon( url( url ) ) )



# DATA PREPROCESSING I: INJURIES & FATALITIES

dat        <- na.omit(dat)                                       # Remove NA
dat$fatal  <- dat$Totalfatalities > 0                            # 1+ fatalities
dat$inj    <- dat$Totalinjuries > 0 & dat$Totalfatalities == 0   # 1+ injuries, 0 fatal
dat$nohurt <- dat$Totalfatalities + dat$Totalinjuries == 0       # Harmless

date.vec   <- strptime(dat$DateTime, format = "%m/%d/%y %H:%M")  # Datetime variables
dat$hour   <- format(date.vec, format = "%H") %>% as.numeric()
dat$month  <- format(date.vec, format = "%b")
dat$day    <- format(date.vec, format = "%a")
dat$day365 <- format(date.vec, format = "%j")
dat$week   <- format(date.vec, format = "%V")



# DATA PREPROCESSING II: NAMED INTERVALS OF TIME

dat <- dat %>% 
  mutate(time.of.day = case_when(hour >= 6 & hour <= 9 ~ "Morning Commute", 
                                 hour >= 16 & hour <= 19 ~ "Evening Commute", 
                                 hour >= 14 & hour <= 15 ~ "School Pickup", 
                                 hour >= 9 & hour <= 13 ~ "Work", 
                                 hour >= 20 & hour <= 23 ~ "Night", 
                                 hour <= 5 & hour >= 0 ~ "Midnight to Dawn"))

dat$harm <- ifelse(test = dat$Totalinjuries > 0 | dat$Totalfatalities > 0, 
                   yes = "Harm", 
                   no = "No Harm")



# DATA PREPROCESSING III: PERMUTATIONS OF INEBRIATION

dat <- dat %>% 
  mutate(d1.substance = case_when(AlcoholUse_Drv1 == "Alcohol" & 
                                  DrugUse_Drv1 == "No Apparent Influence" ~ "Alcohol", 
                                  AlcoholUse_Drv1 == "No Apparent Influence" & 
                                  DrugUse_Drv1 == "Drugs" ~ "Drugs", 
                                  AlcoholUse_Drv1 == "Alcohol" & 
                                  DrugUse_Drv1 == "Drugs" ~ "Alcohol and Drugs", 
                                  AlcoholUse_Drv1 == "No Apparent Influence" & 
                                  DrugUse_Drv1 == "No Apparent Influence" ~ "No Apparent Influence"))

dat <- dat %>% 
  mutate(d2.substance = case_when(AlcoholUse_Drv2 == "Alcohol" & 
                                  DrugUse_Drv2 == "No Apparent Influence" ~ "Alcohol", 
                                  AlcoholUse_Drv2 == "No Apparent Influence" & 
                                  DrugUse_Drv2 == "Drugs" ~ "Drugs", 
                                  AlcoholUse_Drv2 == "Alcohol" & 
                                  DrugUse_Drv2 == "Drugs" ~ "Alcohol and Drugs", 
                                  AlcoholUse_Drv2 == "No Apparent Influence" & 
                                  DrugUse_Drv2 == "No Apparent Influence" ~ "No Apparent Influence"))



# DATA PREPROCESSING IV: AGE CATEGORIES

dat$age.cat <- case_when(dat$Age_Drv1 >= 0 & 
                         dat$Age_Drv1 <= 18 ~ "Youth", 
                         dat$Age_Drv1 >= 19 & 
                         dat$Age_Drv1 <= 25 ~ "Young Adult", 
                         dat$Age_Drv1 >= 26 & 
                         dat$Age_Drv1 <= 64 ~ "Adult", 
                         dat$Age_Drv1 >= 65 ~ "Senior")

```











Fiction
=====================================  


Inputs {.sidebar}
-------------------------------------
Story Selector

```{r}

```

Outputs
-------------------------------------
Fictions I Have Written

```{r}

```
























Comics
=====================================  


Inputs {.sidebar}
-------------------------------------
Story Selector

```{r}

```


Outputs
-------------------------------------
Storylines from Lines

```{r}

```



















Poetry
=====================================  


Inputs {.sidebar}
-------------------------------------
Poem Selector

```{r}

```

Outputs
-------------------------------------
English Language Arts Freeform

```{r}

```
























Miscellaneous
=====================================  


Inputs {.sidebar}
-------------------------------------
Other Selector

```{r}

```

Outputs
-------------------------------------
Other Finished Projects (Not For Sale)

```{r}

```

